# Generated by Django 5.1.3 on 2024-11-14 08:59

import transactions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FXTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_id', models.CharField(max_length=100)),
                ('input_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[transactions.models.validate_positive])),
                ('input_currency', models.CharField(max_length=10, validators=[transactions.models.validate_currency])),
                ('output_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[transactions.models.validate_positive])),
                ('output_currency', models.CharField(max_length=10, validators=[transactions.models.validate_currency])),
                ('date_of_transaction', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
