# Generated by Django 5.1.3 on 2024-11-20 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_currency', models.CharField(max_length=3)),
                ('output_currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UserCurrencyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal_places', models.PositiveIntegerField(default=2)),
                ('preferred_pairs', models.ManyToManyField(to='transactions.currencypair')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
