# Generated by Django 5.1.3 on 2024-11-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_currencypair_usercurrencypreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercurrencypreference',
            name='preferred_pairs',
        ),
        migrations.RemoveField(
            model_name='usercurrencypreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='CurrencyPair',
        ),
        migrations.DeleteModel(
            name='UserCurrencyPreference',
        ),
    ]
