# Generated by Django 5.1.3 on 2024-11-21 12:57

import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_fxtransaction_input_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxtransaction',
            name='input_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[transactions.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='fxtransaction',
            name='output_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[transactions.models.validate_positive]),
        ),
    ]
